version: "3.8"

services:
    timescale:
        image: timescale/timescaledb:latest-pg12
        container_name: timescale_gark
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - ./pg-database:/var/lib/postgresql/data
    
    pgadmin:
        container_name: pgadmin_gark
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - 5050:80
        depends_on:
            - timescale
    
    jupyterlab:
        container_name: jupyter_gark
        env_file:
            - .env
        build: ./notebooks
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/work