version: "3.8"

services:
    timescale:
        image: timescale/timescaledb:latest-pg12
        container_name: timescale_gark
        restart: unless-stopped
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - ./pg-database:/var/lib/postgresql/data
    
    pgadmin:
        container_name: pgadmin_gark
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
        ports:
            - 5050:80
        depends_on:
            - timescale
    
    jupyterlab:
        container_name: jupyter_gark
        env_file:
            - .env
        build: ./notebooks
        ports:
            - "8888:8888"
        volumes:
            - ./notebooks:/home/jovyan/work
    
    fastapi:
        container_name: fast_gark
        env_file:
            - .env
        build: ./fastapi
        command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
        volumes:
            - ./fastapi:/app
        ports:
            - 8000:8000
        depends_on:
            - timescale
        restart: always

    # mongodb:
    #     container_name: mongodb_gark
    #     image: mongo:5.0.2
    #     volumes:
    #     - ./mongo_database:/data/db
    #     ports:
    #     - "27017:27017"
    #     environment:
    #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    #     - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    #     restart: 
    #         always
    # mongoexpress:
    #     image: mongo-express
    #     container_name: mongoexp_gark
    #     ports:
    #         - "8081:8081"
    #     links:
    #         - mongodb
    #     environment: 
    #         - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017

    # neo4j:
    #     container_name: neo4j_gark
    #     image: neo4j:4.3.0-enterprise
    #     restart: always
    #     volumes: 
    #         - ./neo-database/data:/data
    #         - ./neo-database/import:/import
    #         - ./neo-database/plugins:/plugins
    #         - ./neo-database/conf:/conf
    #     ports:
    #         - 7474:7474
    #         - 7687:7687
    #     environment:
    #         - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    #         - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    #         - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    #         - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    #         - NEO4J_dbms_memory_pagecache_size=8G
    #         - NEO4j_dbms_memory_heap_initial__size=8G
    #         - NEO4J_dbms_memory_heap_max__size=16G
        
    