CREATE TABLE stock_sql (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    description TEXT NOT NULL,
    figi TEXT NOT NULL,
    type TEXT NOT NULL
)

CREATE TABLE holdings_sql (
    etf_id INTEGER NOT NULL, 
    holding_id INTEGER NOT NULL,
    dt DATE NOT NULL, 
    shares NUMERIC,
    weight NUMERIC, 
    PRIMARY KEY (etf_id, holding_id, dt),
    CONSTRAINT fk_etf FOREIGN KEY (etf_id) REFERENCES stock_sql (id),
    CONSTRAINT fk_holding FOREIGN KEY (holding_id) REFERENCES stock_sql (id)
)

CREATE TABLE dividend_sql (
    stock_id INTEGER NOT NULL,
    exDate DATE NOT NULL,
    paymentDate DATE NOT NULL,
    recordDate DATE NOT NULL,
    amount NUMERIC (4, 2) NOT NULL,
    PRIMARY KEY (stock_id, paymentDate),
    CONSTRAINT fk_stock FOREIGN KEY (stock_id) REFERENCES stock_sql (id)
)

CREATE TABLE stock_price_sql (
    stock_id INTEGER NOT NULL,
    dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    open NUMERIC (6, 2) NOT NULL, 
    high NUMERIC (6, 2) NOT NULL,
    low NUMERIC (6, 2) NOT NULL,
    close NUMERIC (6, 2) NOT NULL, 
    volume NUMERIC NOT NULL,
    PRIMARY KEY (stock_id, dt),
    CONSTRAINT fk_stock FOREIGN KEY (stock_id) REFERENCES stock_sql (id)
)

CREATE TABLE patterns (
    stock_id INTEGER NOT NULL,
    dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	cdl2crows NUMERIC,
    cdl3blackcrows NUMERIC,
    cdl3inside NUMERIC,
    cdl3linestrike NUMERIC,
    cdl3outside NUMERIC,
    cdl3starsinsouth NUMERIC,
    cdl3whitesoldiers NUMERIC,
    cdlabandonedbaby NUMERIC,
    cdladvanceblock NUMERIC,
    cdlbelthold NUMERIC,
    cdlbreakaway NUMERIC,
    cdlclosingmarubozu NUMERIC,
    cdlconcealbabyswall NUMERIC,
    cdlcounterattack NUMERIC,
    cdldarkcloudcover NUMERIC,
    cdldoji NUMERIC,
    cdldojistar NUMERIC,
    cdldragonflydoji NUMERIC,
    cdlengulfing NUMERIC,
    cdleveningdojistar NUMERIC,
    cdleveningstar NUMERIC,
    cdlgapsidesidewhite NUMERIC,
    cdlgravestonedoji NUMERIC,
    cdlhammer NUMERIC,
    cdlhangingman NUMERIC,
    cdlharami NUMERIC,
    cdlharamicross NUMERIC,
    cdlhighwave NUMERIC,
    cdlhikkake NUMERIC,
    cdlhikkakemod NUMERIC,
    cdlhomingpigeon NUMERIC,
    cdlidentical3crows NUMERIC,
    cdlinneck NUMERIC,
    cdlinvertedhammer NUMERIC,
    cdlkicking NUMERIC,
    cdlkickingbylength NUMERIC,
    cdlladderbottom NUMERIC,
    cdllongleggeddoji NUMERIC,
    cdllongline NUMERIC,
    cdlmarubozu NUMERIC,
    cdlmatchinglow NUMERIC,
    cdlmathold NUMERIC,
    cdlmorningdojistar NUMERIC,
    cdlmorningstar NUMERIC,
    cdlonneck NUMERIC,
    cdlpiercing NUMERIC,
    cdlrickshawman NUMERIC,
    cdlrisefall3methods NUMERIC,
    cdlseparatinglines NUMERIC,
    cdlshootingstar NUMERIC,
    cdlshortline NUMERIC,
    cdlspinningtop NUMERIC,
    cdlstalledpattern NUMERIC,
    cdlsticksandwich NUMERIC,
    cdltakuri NUMERIC,
    cdltasukigap NUMERIC,
    cdlthrusting NUMERIC,
    cdltristar NUMERIC,
    cdlunique3river NUMERIC,
    cdlupsidegap2crows NUMERIC,
    cdlxsidegap3methods NUMERIC,
    PRIMARY KEY (stock_id, dt),
    CONSTRAINT fk_stock FOREIGN KEY (stock_id) REFERENCES tickers (id)
)
