name: ARK Funds Stock Data Download

on:
  push:
    paths:
      - .github/workflows/ARK.yml
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'
    
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Get ARRK csv
        uses: githubocto/flat@v3
        with:   
          http_url: https://ark-funds.com/wp-content/fundsiteliterature/csv/ARK_INNOVATION_ETF_ARKK_HOLDINGS.csv
          downloaded_filename: ARKK.csv

      
            
